spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/members
    driverClassName: com.mysql.cj.jdbc.Driver
    #    url: jdbc:h2:mem:schoolDb
    username: lijy1
    password: xsw2!QAZ
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
    open-in-view: false
    defaultPageSize: 10

server:
  port: 8081